apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/vitieu98/udagram-api-user:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
            - name: URL
              value: "http://localhost:8100"
            - name: JWT_SECRET
              value: "testing"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_HOST
              value: "database-1.cbhmv8h0ffes.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_PASSWORD
              value: "vitieu98"
            - name: POSTGRES_USERNAME
              value: "postgres"